site_name: openSUSE User Documentation Project
repo_url: https://github.com/openSUSE/openSUSE-docs-revamped-temp
edit_uri: ""

plugins:
    - search:
        prebuild_index: true
    - git-revision-date
    #- mkdocs-versioning:
    #    version: 0.3.1
    - pdf-export:
        verbose: true
        media_type: print
        #enable PDF printing by running "export ENABLE_PDF_EXPORT=1"
        enabled_if_env: ENABLE_PDF_EXPORT
        #comment out the next two options to make every page have its own PDF
        combined: true
        combined_output_path: docs.pdf
theme:
    name: material
    font:
        code: Fira Code
        text: Noto Sans TC
    custom_dir: overrides
    palette:
        scheme: preference
        primary: green
        accent: red
    logo: image/Button-filled-colour.png
    favicon: image/geeko-color.png
    features:
        - navigation.sections
        - navigation.instant
        - navigation.tracking
        - navigation.expand
        # - navigation.tabs
        # - navigation.tabs.sticky
    icon:
        repo: fontawesome/brands/github

extra:
    logo: image/geeko-color.png
    social:
    - icon: button-filled-monochrome
      link: https://www.opensuse.org
      name: openSUSE Main Website
    - icon: fontawesome/brands/github
      link: https://github.com/openSUSE
      name: openSUSE GitHub

extra_css: 
    - styles.css
      
markdown_extensions:
    - admonition
    - def_list
    - pymdownx.details
    - pymdownx.superfences
    - toc:
        permalink: ⚓︎
        toc_depth: 5

nav:
    - Home: index.md
    - Version Selector: "../"
    - Before installing:
        - Choosing a distribution: pick_an_image.md
        - Preparing the installation media: image_choice.md
    - Installing: yast_installer.md
    - Distro basics:
        - Post-installation best-of: best_of_post.md
        - MicroOS Desktop: microos_getting_started.md
        - KDE Plasma basics: kde.md
        - GNOME basics: ""
        - Interlude -- Fundamental openSUSE concepts:
            - Zypper: zypper.md
            - YaST2: ""
            - Updating, upgrading, snapshots best practices: updating_upgrading.md
            - Snapper and Btrfs: snapper.md
        - Additional software: 
            - Software procurement: alternative_procurement.md
            - Building from source: ""
        - Troubleshooting with autonomy: ""
    - Completing and fine-tuning your setup:
        - Audio & Video:
            - Codecs: codecs.md
            - Pipewire: pipewire.md
        - Graphic Drivers: 
            - Getting started: install_proprietary.md
            - Dual GPUs ("Optimus"): hybrid_graphics.md
        - Peripherals:
            - Bluetooth: bluetooth.md
            - KDE Connect: kdeconnect.md
            - Printers & scanners:
                - Printers: printersetc.md
        - Setting up a containerized environment: install_podman.md
        - Power management: power.md
        - Advanced fine-tunings:
            - Transparent compression (zstd): zstd.md
    - Giving back to the community:
        - The art of reporting bugs: ""
        - Resources: ""
        - Other sources of documentation: reference_docs.md
        - Contribute to this docs: 
            - Markdown flavour: markdown.md
            - Todo: todo.md
        - A contributor's checklist: ""
